website:
  content_path: "ai-safety-site/content/en"

data_dir: "data"

semantic_scholar:
  api_key: "${SEMANTIC_SCHOLAR_API_KEY}"

anthropic:
  api_key: "${ANTHROPIC_API_KEY}"

supabase:
  url: "${SUPABASE_URL}"
  key: "${SUPABASE_KEY}"