[build]
  base = "ai-safety-site"
  publish = "public"
  command = """
    pip install -r site-requirements.txt &&
    hugo --themesDir themes
  """

[build.environment]
  HUGO_VERSION = "0.136.2"
  HUGO_ENV = "production"
  HUGO_ENABLEGITINFO = "true"
  HUGO_EXTENDED = "true"

[context.production.environment]
  HUGO_ENV = "production"

[context.deploy-preview]
  command = """
    pip install -r site-requirements.txt &&
    hugo --buildFuture -b $DEPLOY_PRIME_URL --themesDir themes
  """

[context.branch-deploy]
  command = """
    pip install -r site-requirements.txt &&
    hugo --buildFuture -b $DEPLOY_PRIME_URL --themesDir themes
  """

[[plugins]]
  package = "@netlify/plugin-sitemap"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"