baseURL = "https://papers.unsearch.org/"
languageCode = "en"
title = "AI Safety Papers"
themesDir = "themes"
theme = "hugo-theme-monochrome"
defaultContentLanguage = "en"
enableEmoji = true
pagerSize = 5
enableGitInfo = true

# Add explicit language configuration
[languages]
  [languages.en]
    languageName = "English"
    weight = 1
    title = "AI Safety Papers"

[taxonomies]
category = "categories"
tag = "tags"
series = "series"

[outputs]
home = ["HTML", "RSS", "JSON"]
